repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt
  - repo: local
    hooks:
      - id: check
        name: Check GitHub Action versions
        entry: go run . check
        language: system
        files: ^\.github/workflows/[^/]+\.ya?ml$
        pass_filenames: false
        stages: [pre-commit]
      - id: lint
        name: Lint GitHub Actions workflows
        entry: go run . lint
        language: system
        files: ^\.github/workflows/[^/]+\.ya?ml$
        pass_filenames: false
        stages: [pre-commit]
      - id: validate
        name: Validate GitHub Actions workflows
        entry: go run . validate
        language: system
        files: ^\.github/workflows/[^/]+\.ya?ml$
        pass_filenames: false
        stages: [pre-commit]
